### ISSUE TITLE
[Bug] Error While Generating Files in _n.ConstantsExtractor

### ISSUE THREAD

**Issue by LinnZawWin** [neronotte/Greg.Xrm#53]
**Describe the bug**
There is an error while the constant files are being generated in _n.ConstantsExtractor tool.

**To Reproduce**
1. Open _n.ConstantsExtractor tool
2. Select one of the solutions with tables
3. Specify the Namespaces and Folder Paths
4. Click Export
5. Error message pops up and no file was generated.

**Expected behavior**
The files are being generated without an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14156926/232235758-c9165270-6eca-43d7-8122-2da2129ef6fd.png)

**Additional context**
This is the stack trace error
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Greg.Xrm.ConstantsExtractor.Core.ConstantExtractorManager.<>c__DisplayClass86_1.<GetOptionsetValuesFromMetadata>b__0(LocalizedLabel lab)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Greg.Xrm.ConstantsExtractor.Core.ConstantExtractorManager.GetOptionsetValuesFromMetadata(OptionSetMetadataBase optionSets)
   at Greg.Xrm.ConstantsExtractor.Core.ConstantExtractorManager.GetGlobalOptionSetsMetadataManager(OptionSetMetadataBase opt)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Greg.Xrm.ConstantsExtractor.Core.ConstantExtractorManager.GetGlobalOptionSets()
   at Greg.Xrm.ConstantsExtractor.Core.ConstantExtractorManager.ExtractConstants()
   at Greg.Xrm.ConstantsExtractor.Views.MainView.<>c__DisplayClass7_0.<Export>b__0(BackgroundWorker worker, DoWorkEventArgs args)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by neronotte** [comment]
Hi Linn,
issue solved on the next version of the tool. Sorry for the delay.
